import React from "react";

import { Container } from "react-bootstrap";
const Privacy = () => {
  return (
    <>
      <Container>
        <h1 className="text-center">Privacy Policy</h1>
        <p className="text-start fs-20 text-secondary mt-5">
          Our Privacy Policy was last updated on 2/10/2022.
        </p>
        <p className="text-start fs-20 text-secondary mt-5">
          This Privacy Policy describes Our policies and procedures on the
          collection, use and disclosure of Your information when You use the
          Service and tells You about Your privacy rights and how the law
          protects You
        </p>
        <p className="text-start fs-20 text-secondary mt-4">
          We use Your Personal data to provide and improve the Service. By using
          the Service, You agree to the collection and use of information in
          accordance with this Privacy Policy.
        </p>
        <h4 className="text-start mt-5">Interpretation and Definitions</h4>
        <p className="text-start fs-20 text-secondary text-decoration-underline mt-4">
          Interpretation
        </p>
        <p className="text-start fs-20 text-secondary  mt-4">
          The words of which the initial letter is capitalized have meanings
          defined under the following conditions. The following definitions
          shall have the same meaning regardless of whether they appear in
          singular or in plural.
        </p>
        <p className="text-start fs-20 text-secondary text-decoration-underline mt-4">
          Definitions
        </p>
        <p className="text-start fs-20 text-secondary  mt-4">
          For the purposes of this Privacy Policy:
        </p>
        <ul>
          <li className="text-start fs-18 text-secondary  mt-1">
            "Account" means a unique account created for You to access our
            Service or parts of our Service.
          </li>
          <li className="text-start fs-18 text-secondary  mt-1">
            "Application" means the software program provided by the Company
            downloaded by You on any electronic device, named Twigs One.
          </li>
          <li className="text-start fs-18 text-secondary  mt-1">
            "Company" (referred to as either "the Company", "We", "Us" or "Our"
            in this Agreement) refers to Twigscorp.
          </li>
          <li className="text-start fs-18 text-secondary  mt-1">
            "Country" refers to United States.
          </li>
          <li className="text-start fs-18 text-secondary  mt-1">
            "Cookies" are small files that are placed on Your computer, mobile
            device or any other device by a website, containing the details of
            Your browsing history on that website among its many uses.
          </li>
          <li className="text-start fs-18 text-secondary  mt-1">
            "Device" means any device that can access the Service such as a
            computer, a cell phone or a digital tablet.
          </li>
          <li className="text-start fs-18 text-secondary  mt-1">
            "Personal Data" is any information that relates to an identified or
            identifiable individual.
          </li>
          <li className="text-start fs-18 text-secondary  mt-1">
            "Service" refers to the Website.
          </li>
          <li className="text-start fs-18 text-secondary  mt-1">
            "Service Provider" means any natural or legal person who processes
            the data on behalf of the Company. It refers to third-party
            companies or individuals employed by the Company to facilitate the
            Service, to provide the Service on behalf of the Company, to perform
            services related to the Service or to assist the Company in
            analyzing how the Service is used.
          </li>
          <li className="text-start fs-18 text-secondary  mt-1">
            "Usage Data" refers to data collected automatically, either
            generated by the use of the Service or from the Service
            infrastructure itself (for example, the duration of a page visit).
          </li>
          <li className="text-start fs-18 text-secondary  mt-1">
            "You" means the individual accessing or using the Service, or the
            company, or other legal entity on behalf of which such individual is
            accessing or using the Service, as applicable.
          </li>
        </ul>
        <h4 className="text-start mt-4">
          Collecting and Using Your Personal Data
        </h4>
        <p className="text-start fs-20 text-secondary text-decoration-underline mt-4">
          Types of Data Collected
        </p>
        <h4 className="text-start mt-4">Personal Data</h4>
        <p className="text-start fs-20 text-secondary mt-4">
          While using Our Service, We may ask You to provide Us with certain
          personally identifiable information that can be used to contact or
          identify You. Personally identifiable information may include, but is
          not limited to:
        </p>
        <ul>
          <li className="text-start fs-18 text-secondary  mt-1">
            First Name and Last Name
          </li>
          <li className="text-start fs-18 text-secondary  mt-1">
            Phone Number:
          </li>
          <li className="text-start fs-18 text-secondary  mt-1">
            Date of Birth:
          </li>
          <li className="text-start fs-18 text-secondary  mt-1">Gender</li>
          <li className="text-start fs-18 text-secondary  mt-1">
            Address, State, Province, ZIP/Postal code, City
          </li>
          <li className="text-start fs-18 text-secondary  mt-1">Usage Data</li>
        </ul>
        <h4 className="text-start mt-4">Usage Data</h4>
        <p className="text-start fs-20 text-secondary mt-4">
          Usage Data is collected automatically when using the Service.
        </p>
        <p className="text-start fs-20 text-secondary mt-4">
          Usage Data may include information such as Your Device's Internet
          Protocol address (e.g., IP address), browser type, browser version,
          the pages of our Service that You visit, the time and date of Your
          visit, the time spent on those pages, unique device identifiers and
          other diagnostic data.
        </p>
        <p className="text-start fs-20 text-secondary mt-4">
          When You access the Service by or through a mobile device, We may
          collect certain information automatically, including, but not limited
          to, the type of mobile device You use, Your mobile device unique ID,
          the IP address of Your mobile device, Your mobile operating system,
          the type of mobile Internet browser You use, unique device identifiers
          and other diagnostic data.
        </p>
        <p className="text-start fs-20 text-secondary mt-4">
          We may also collect information that Your browser sends whenever You
          visit our Service or when You access the Service by or through a
          mobile device.
        </p>
        <h4 className="text-start mt-4">
          Information Collected while Using the Application
        </h4>
        <p className="text-start fs-20 text-secondary mt-4">
          While using Our Application, in order to provide features of Our
          Application, We may collect, with Your prior permission:
        </p>
        <ul>
          <li className="text-start fs-18 text-secondary  mt-1">
            Information regarding your location
          </li>
          <p className="text-start fs-20 text-secondary ">
            We use this information to provide features of Our Service, to
            improve and customize Our Service. The information may be uploaded
            to the Company's servers and/or a Service Provider's server or it
            may be simply stored on Your device.
          </p>
          <p className="text-start fs-20 text-secondary mt-4">
            You can enable or disable access to this information at any time,
            through Your Device settings.
          </p>
        </ul>
        <h4 className="text-start mt-4">Use of Your Personal Data</h4>
        <p className="text-start fs-20 text-secondary mt-4">
          The Company may use Personal Data for the following purposes:
        </p>
        <ul>
          <li className="text-start fs-18 text-secondary  mt-1">
            To provide and maintain our Service, including to monitor the usage
            of our Service.
          </li>
          <li className="text-start fs-18 text-secondary  mt-1">
            To manage Your Account: to manage Your registration as a user of the
            Service. The Personal Data You provide can give You access to
            different functionalities of the Service that are available to You
            as a registered user.
          </li>
          <li className="text-start fs-18 text-secondary  mt-1">
            For the performance of a contract: the development, compliance and
            undertaking of the purchase contract for the products, items or
            services You have purchased or of any other contract with Us through
            the Service.
          </li>
          <li className="text-start fs-18 text-secondary  mt-1">
            To contact You: To contact You by email, telephone calls, SMS, or
            other equivalent forms of electronic communication, such as a mobile
            application's push notifications regarding updates or informative
            communications related to the functionalities, products or
            contracted services, including the security updates, when necessary
            or reasonable for their implementation.
          </li>
          <li className="text-start fs-18 text-secondary  mt-1">
            To provide You with news, special offers and general information
            about other goods, services and events which we offer that are
            similar to those that you have already purchased or enquired about
            unless You have opted not to receive such information.
          </li>
          <li className="text-start fs-18 text-secondary  mt-1">
            To manage Your requests: To attend and manage Your requests to Us.
          </li>
          <li className="text-start fs-18 text-secondary  mt-1">
            For business transfers: We may use Your information to evaluate or
            conduct a merger, divestiture, restructuring, reorganization,
            dissolution, or other sale or transfer of some or all of Our assets,
            whether as a going concern or as part of bankruptcy, liquidation, or
            similar proceeding, in which Personal Data held by Us about our
            Service users is among the assets transferred.
          </li>
          <li className="text-start fs-18 text-secondary  mt-1">
            {" "}
            For other purposes: We may use Your information for other purposes,
            such as data analysis, identifying usage trends, determining the
            effectiveness of our promotional campaigns and to evaluate and
            improve our Service, products, services, marketing and your
            experience.We may share Your personal information in the following
            situations:
          </li>
          <li className="text-start fs-18 text-secondary  mt-1">
            With Service Providers: We may share Your personal information with
            Service Providers to monitor and analyze the use of our Service, for
            payment processing, to contact You.
          </li>
          <li className="text-start fs-18 text-secondary  mt-1">
            For business transfers: We may share or transfer Your personal
            information in connection with, or during negotiations of, any
            merger, sale of Company assets, financing, or acquisition of all or
            a portion of Our business to another company.
          </li>
          <li className="text-start fs-18 text-secondary  mt-1">
            With Affiliates: We may share Your information with Our affiliates,
            in which case we will require those affiliates to honor this Privacy
            Policy. Affiliates include Our parent company and any other
            subsidiaries, joint venture partners or other companies that We
            control or that are under common control with Us.
          </li>
          <li className="text-start fs-18 text-secondary  mt-1">
            With business partners: We may share Your information with Our
            business partners to offer You certain products, services or
            promotions.
          </li>
          <li className="text-start fs-18 text-secondary  mt-1">
            With other users: when You share personal information or otherwise
            interact in the public areas with other users, such information may
            be viewed by all users and may be publicly distributed outside.
          </li>
          <li className="text-start fs-18 text-secondary  mt-1">
            With Your consent: We may disclose Your personal information for any
            other purpose with Your consent.
          </li>
        </ul>
        <h4 className="text-start mt-4">Retention of Your Personal Data</h4>
        <p className="text-start fs-20 text-secondary  mt-4">
          The Company will retain Your Personal Data only for as long as is
          necessary for the purposes set out in this Privacy Policy. We will
          retain and use Your Personal Data to the extent necessary to comply
          with our legal obligations (for example, if we are required to retain
          your data to comply with applicable laws), resolve disputes, and
          enforce our legal agreements and policies.The Company will also retain
          Usage Data for internal analysis purposes. Usage Data is generally
          retained for a shorter period of time, except when this data is used
          to strengthen the security or to improve the functionality of Our
          Service, or We are legally obligated to retain this data for longer
          time periods.
        </p>
        <h4 className="text-start mt-4">Transfer of Your Personal Data</h4>
        <p className="text-start fs-20 text-secondary  mt-4">
          Your information, including Personal Data, is processed at the
          Company's operating offices and in any other places where the parties
          involved in the processing are located. It means that this information
          may be transferred to — and maintained on — computers located outside
          of Your state, province, country or other governmental jurisdiction
          where the data protection laws may differ than those from Your
          jurisdiction.
        </p>
        <p className="text-start fs-20 text-secondary  mt-4">
          Your consent to this Privacy Policy followed by Your submission of
          such information represents Your agreement to that transfer.
        </p>
        <p className="text-start fs-20 text-secondary  mt-4">
          The Company will take all steps reasonably necessary to ensure that
          Your data is treated securely and in accordance with this Privacy
          Policy and no transfer of Your Personal Data will take place to an
          organization or a country unless there are adequate controls in place
          including the security of Your data and other personal information.
        </p>
        <h4 className="text-start mt-4">Disclosure of Your Personal Data</h4>
        <h4 className="text-start mt-2">Business Transactions</h4>

        <p className="text-start fs-20 text-secondary  mt-4">
          If the Company is involved in a merger, acquisition or asset sale,
          Your Personal Data may be transferred. We will provide notice before
          Your Personal Data is transferred and becomes subject to a different
          Privacy Policy.
        </p>
        <h4 className="text-start mt-4">Law enforcement</h4>

        <p className="text-start fs-20 text-secondary  mt-4">
          Under certain circumstances, the Company may be required to disclose
          Your Personal Data if required to do so by law or in response to valid
          requests by public authorities (e.g. a court or a government agency).
        </p>
        <h4 className="text-start mt-4">Other legal requirements</h4>

        <p className="text-start fs-20 text-secondary  mt-4">
          The Company may disclose Your Personal Data in the good faith belief
          that such action is necessary to:
        </p>
        <ul>
          <li className="text-start fs-18 text-secondary  mt-1">
            {" "}
            Comply with a legal obligation
          </li>
          <li className="text-start fs-18 text-secondary  mt-1">
            {" "}
            Protect and defend the rights or property of the Company
          </li>
          <li className="text-start fs-18 text-secondary  mt-1">
            Prevent or investigate possible wrongdoing in connection with the
            Service
          </li>
          <li className="text-start fs-18 text-secondary  mt-1">
            Protect the personal safety of Users of the Service or the public
          </li>
          <li className="text-start fs-18 text-secondary  mt-1">
            Protect against legal liability
          </li>
        </ul>
        <h4 className="text-start mt-4">Security of Your Personal Data</h4>

        <p className="text-start fs-20 text-secondary  mt-4">
          The security of Your Personal Data is important to Us, but remember
          that no method of transmission over the Internet, or method of
          electronic storage is 100% secure. While We strive to use commercially
          acceptable means to protect Your Personal Data, We cannot guarantee
          its absolute security.
        </p>
        <h4 className="text-start mt-4">
          Detailed Information on the Processing of Your Personal Data
        </h4>

        <p className="text-start fs-20 text-secondary  mt-4">
          The Service Providers We use may have access to Your Personal Data.
          These third-party vendors collect, store, use, process and transfer
          information about Your activity on Our Service in accordance with
          their Privacy Policies.Analytics
        </p>
        <h4 className="text-start mt-4">Analytics</h4>

        <p className="text-start fs-20 text-secondary  mt-4">
          We may use third-party Service providers to monitor and analyze the
          use of our Service.
        </p>
        <ul>
          <li className="text-start fs-18 text-secondary  mt-1">
            Google Analytics
          </li>
          <li className="text-start fs-18 text-secondary  mt-1">
            Firebase Analytics
          </li>
        </ul>
        <h4 className="text-start mt-4">Children's Privacy</h4>

        <p className="text-start fs-20 text-secondary  mt-4">
          Our Service does not address anyone under the age of 13. We do not
          knowingly collect personally identifiable information from anyone
          under the age of 13. If You are a parent or guardian and You are aware
          that Your child has provided Us with Personal Data, please contact Us.
          If We become aware that We have collected Personal Data from anyone
          under the age of 13 without verification of parental consent, We take
          steps to remove that information from Our servers. If We need to rely
          on consent as a legal basis for processing Your information and Your
          country requires consent from a parent, We may require Your parent's
          consent before We collect and use that information.
        </p>
        <h4 className="text-start mt-4">Links to Other Websites</h4>

        <p className="text-start fs-20 text-secondary  mt-4">
          Our Service may contain links to other websites that are not operated
          by Us. If You click on a third-party link, You will be directed to
          that third party's site. We strongly advise You to review the Privacy
          Policy of every site You visit. We have no control over and assume no
          responsibility for the content, privacy policies or practices of any
          third-party sites or services.
        </p>
        <h4 className="text-start mt-4">Changes to this Privacy Policy</h4>

        <p className="text-start fs-20 text-secondary  mt-4">
          We may update Our Privacy Policy from time to time. We will notify You
          of any changes by posting the new Privacy Policy on this page.
        </p>
        <p className="text-start fs-20 text-secondary  mt-4">
          We will let You know via email and/or a prominent notice on Our
          Service, prior to the change becoming effective and update the "Last
          updated" date at the top of this Privacy Policy. You are advised to
          review this Privacy Policy periodically for any changes. Changes to
          this Privacy Policy are effective when they are posted on this page.
        </p>
        <h4 className="text-start mt-4">Contact Us</h4>

        <p className="text-start fs-20 text-secondary  mt-4">
          If you have any questions about this Privacy Policy, You can contact
          us:
        </p>
        <ul>
          <li className="text-start fs-18 text-secondary  mt-1">
            By visiting the contact page on our website
          </li>
          <li className="text-start fs-18 text-secondary  mt-1">
            By sending us an email: support@twigscorp.com
          </li>
        </ul>
      </Container>
    </>
  );
};
export default Privacy;
